version: 2

models:
  - name: fct_request_hotspots
    description: SQL-native spatial hotspot clusters at 30d and 90d windows.
    columns:
      - name: cluster_id
        tests:
          - not_null
      - name: window_days
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [30, 90]
      - name: comm_plan_name
        tests:
          - not_null
      - name: request_count
        tests:
          - not_null
      - name: open_request_count
        tests:
          - not_null
      - name: closed_or_referred_count
        tests:
          - not_null

  - name: fct_city_daily_metrics
    description: Citywide daily request pressure metrics (all neighborhoods combined).
    columns:
      - name: metric_date
        tests:
          - not_null
      - name: request_count
        tests:
          - not_null
      - name: open_request_count
        tests:
          - not_null
      - name: aging_open_request_count
        tests:
          - not_null
      - name: duplicate_child_request_count
        tests:
          - not_null
      - name: median_resolution_days
        tests:
          - not_null
      - name: closed_request_count
        tests:
          - not_null
      - name: opened_request_count_3d
        tests:
          - not_null
      - name: opened_request_count_7d
        tests:
          - not_null
      - name: closed_request_count_3d
        tests:
          - not_null
      - name: closed_request_count_7d
        tests:
          - not_null

  - name: fct_city_service_daily_metrics
    description: Citywide daily service volume and busy/light day indicators.
    columns:
      - name: metric_date
        tests:
          - not_null
      - name: service_name
        tests:
          - not_null
      - name: request_count
        tests:
          - not_null
      - name: is_busy_day
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]
      - name: is_light_day
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

  - name: fct_neighborhood_daily_metrics
    description: Daily request pressure metrics by neighborhood grain (comm plan, district, ZIP).
    columns:
      - name: metric_date
        tests:
          - not_null
      - name: grain_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['comm_plan_name', 'council_district', 'zipcode']
      - name: grain_value
        tests:
          - not_null
      - name: request_count
        tests:
          - not_null
      - name: open_request_count
        tests:
          - not_null
      - name: aging_open_request_count
        tests:
          - not_null
      - name: duplicate_child_request_count
        tests:
          - not_null
      - name: median_resolution_days
        tests:
          - not_null
      - name: closed_request_count
        tests:
          - not_null
      - name: opened_request_count_3d
        tests:
          - not_null
      - name: opened_request_count_7d
        tests:
          - not_null
      - name: closed_request_count_3d
        tests:
          - not_null
      - name: closed_request_count_7d
        tests:
          - not_null

  - name: fct_neighborhood_service_daily_metrics
    description: Daily service volume and busy/light day indicators by neighborhood grain.
    columns:
      - name: metric_date
        tests:
          - not_null
      - name: grain_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['comm_plan_name', 'council_district', 'zipcode']
      - name: grain_value
        tests:
          - not_null
      - name: service_name
        tests:
          - not_null
      - name: request_count
        tests:
          - not_null
      - name: is_busy_day
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]
      - name: is_light_day
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

  - name: fct_neighborhood_frustration_index
    description: Rolling 30d/90d frustration index and components by neighborhood grain.
    columns:
      - name: as_of_date
        tests:
          - not_null
      - name: grain_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['comm_plan_name', 'council_district', 'zipcode']
      - name: grain_value
        tests:
          - not_null
      - name: window_days
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [30, 90]
      - name: frustration_index
        tests:
          - not_null
